### ISSUE TITLE
The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by fushini** [mzomparelli/zVirtualDesktop#235]
Update to version 1.0.93 fails on Windows 10 Enterprise 10.0.17134 with “The specified executable is not a valid application for this OS platform”. 

When the update fails, the zVirtualDesktop.exe file is removed from the system.

EDIT: Is it possible to disable automatic updates?

**Comment by mzomparelli** [comment]
That's Windows 10 1709 version, right?

zVD only auto-updates when it determines you are running a version compiled for a different Windows 10 version. Otherwise, you will have a choice to update.

The reason it removed the file is due to a failed download of the update. I will work on a solution for that.

**Comment by fushini** [comment]
Not sure, but according to https://en.m.wikipedia.org/wiki/Windows_10_version_history, this is Windows 1803.

**Comment by mzomparelli** [comment]
Thanks for that info. Were you able to manually download zVD and run 1.0.93.0? I will work on a solution to verify the download so to avoid this in the future.

**Comment by fushini** [comment]
A download copy of the recent version from the homepage (cannot confirm it is 1.0.93.0) fails with the same error and the file is removed from the system.

**Comment by fushini** [comment]
I did not purchase the license, and do not know the details, but we have zVD installed across multiple Win10 machines. None can update 1.0.92.0 to 1.0.93.0 or run the 1.0.93.0 file from the main page. We have one machine that was just rebuilt and cannot activate zVD from 1.0.92.0. The user receives a “Please update to the current version and try again.”

Two questions:
[1] Is there any way to activate a license on 1.0.92.0?
[2] Is it possible to disable the update popup so we stop updating by mistake to a version that does not run on our machines?

**Comment by mzomparelli** [comment]
I think you are just having an issue with updating. By default, the main page link is to the 1809 version. When you run that it should see you are on 1803 and download the right version. Since you apparently have complications downloading, let's try downloading the 1803 version manually.

https://zomp.co/Files.aspx?id=zVDEXE_1803

or for zip file

https://zomp.co/Files.aspx?id=zVD1803

Let me know if that link helps.

**Comment by mzomparelli** [comment]
As far as this updating bug. I'm going to retain the original exe when trying to update and if the download fails I will just restore your current version.

As far as activating a previous version, I prevented that when I was making activation process changes. I can remove that restriction now, but I can only do that for future versions. 

I'm confident that downloading using the links provided will resolve your issue.

**Comment by mzomparelli** [comment]
I just published a new 1803 in case I accidentally published a faulty build.

https://zomp.co/Files.aspx?id=zVD1803
https://zomp.co/Files.aspx?id=zVDEXE_1803

**Comment by mzomparelli** [comment]
The downloader will now copy the existing exe before trying to download the updated exe. If the download fails the copied file will be restored and started.

**Comment by fushini** [comment]
Sorry for the delay. We have moved our machines over to the 1803 binary linked above and that has resolved the immediate issues. We can use zVD w/o being prompted to update.

If we force an update, we still get the ‘not valid application error’, but there’s no reason for us to force an update.

**Comment by mzomparelli** [comment]
I think you downloaded before I published the version that fixes the downloader. Can you download again and test the force update to see if you get that error? It should not give you that error anymore and instead when it fails it will restore your current version.

**Comment by fushini** [comment]
I downloaded the file from:
https://zomp.co/Files.aspx?id=zVD

This file gets stuck in an unending loop on startup. I get the ‘downloading update was unsuccessful’ box, hit ok, then the updater restarts and the process repeats.

**Comment by mzomparelli** [comment]
Thanks for trying. I will work on fixing that.

**Comment by mzomparelli** [comment]
The loop happened because you download a new 1809 version so that was the one that backed up. When running a version that is not for your OS then it will auto download the appropriate build. This got you in the loop.

Try downloading 1.0.93.1 from the 1803 link I gave you earlier and test a force update. Since the update will fail on your machine it will restore the 1803 version properly.

**Comment by fushini** [comment]
We are having the same update issues trying to update to 1.0.94. The downloader gets stuck in an endless loop. Tries to download update, fails, reverts back to 1.0.93.1, tries to download update, etc.

We tried downloading the program from the main page (https://zomp.co/Files.aspx?id=zVD) but that immediately tries to update and gets stuck in the loop. We cannot revert back to 1.0.93.1 - the program asks us to reactivate but requires the latest version.

**Comment by mzomparelli** [comment]
The reactivate is expected as I have made some changes to this part. If you can 1.0.94 to run then I can help update you license if needed, but you can also just reactivate yourself.

Please send me you Win10 version and I will help you get the correct zVD build. You can get this info by typing WINVER in the run dialog.

**Comment by fushini** [comment]
Thanks for the quick reply. We are on version 1803 build 17134.1304

**Comment by mzomparelli** [comment]
Try this link:

https://zomp.co/Files.aspx?id=zVD1803

**Comment by fushini** [comment]
Thanks again for the reply. The linked file immediately tries to update and gets stuck in the update loop, but it looks like that can be resolved by removing all the non-settings files in the zVD AppData folder. Our virus scanner quarantines the file as infected. We will have to see if our IT department will whitelist the update.

**Comment by mzomparelli** [comment]
I might have published the wrong build. Let me create new builds.

**Comment by mzomparelli** [comment]
Try the link again. I just pushed a new build.

https://zomp.co/Files.aspx?id=zVD1803

**Comment by mzomparelli** [comment]
Also, it might be possible that it can't update properly due to IT restrictions.

**Comment by mzomparelli** [comment]
What anti-virus are you using that is blocking the executable? I know that it can be hard to trust an app after seeing that, but I assure you that nothing malicious is happening. Nonetheless, I want to get to the bottom of why an anti-virus would say otherwise.

**Comment by mzomparelli** [comment]
I just realized that while I compiled a new 1803 version I forgot to actually put it on the server so only if you click the link now will you get the new build.

https://zomp.co/Files.aspx?id=zVD1803

**Comment by mzomparelli** [comment]
How's the new builds working out for you? I hope everything is working. Please let me know if your issue persists.

**Comment by mzomparelli** [comment]
Closing this issue. Please create a new issue if still having problems.
